apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dcr-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dcr-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dcr-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "dcr-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dcr-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: {{ index .Values.secretRefs 0 }}
              key: db_host
        - name: DB_PORT
          value: {{ .Values.database.port | quote }}
        - name: DB_NAME
          value: {{ .Values.database.name | quote }}
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ index .Values.secretRefs 0 }}
              key: db_username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ index .Values.secretRefs 0 }}
              key: db_password
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: {{ index .Values.secretRefs 0 }}
              key: redis_host
        - name: REDIS_PORT
          value: {{ .Values.redis.port | quote }}
        - name: KEYCLOAK_ADMIN_URL
          value: {{ .Values.config.dcr.keycloak.adminUrl | quote }}
        - name: KEYCLOAK_ADMIN_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ index .Values.secretRefs 0 }}
              key: keycloak_client_id
        - name: KEYCLOAK_ADMIN_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ index .Values.secretRefs 0 }}
              key: keycloak_client_secret
        envFrom:
        - configMapRef:
            name: {{ .Values.configMapRef.name }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        {{- toYaml .Values.volumeMounts | nindent 10 }}
      volumes:
      {{- toYaml .Values.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
